- README.md
I always like when there is a very explicit section for all of the configuration options in an action. This PR adds a table describing each option, including `GH_ENTERPRISE_URL` which didn't seem to be mentioned in the README before.
> Add explicit documentation on configuration options and their descriptions

- README.md
This adds an example of one way to run this tool against multiple orgs.
fixes #12 
cc/ @hopkinsth
> Add multiple org example to README

- README.md
* Remove the unnecessary checkout
* Use the automatic GITHUB_TOKEN for issues creation
> docs: simplify the example workflow

- stale_repos.py
> Skip report if no stale repos exist

- README.md
- stale_repos.py
- test_stale_repos.py
> Exempt by name

- stale_repos.py
- test_stale_repos.py
> fix: handle private temp forks which dont have topics

- .github/linters/isort.cfg
> Make isort and black agree on import sort order

- README.md
peter-evans/create-issue-from-file from v4 to v5
> Update issuecreation action to v5

- README.md
adding reference to github-ospo
> Update README.md to include reference to github-ospo

- stale_repos.py
fixes #93 
strip out spaces for people like me that dont follow the directions
> strip out spaces for people like me that dont follow the directions

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-image.yml
- .github/workflows/linter.yaml
- .github/workflows/major-version-updater.yml
- .github/workflows/python-package.yml
- .github/workflows/release-drafter.yml
- .github/workflows/use-action.yml
- README.md
Based on https://github.com/github/stale-repos/pull/85
specifically:
- [CHECKOV](https://github.com/github/stale-repos/actions/runs/7982188180/job/21795271928?pr=85#step:4:199)
- set correct permissions for each GitHub Action, ensuring default is read-only on contents
- [PYLINT](https://github.com/github/stale-repos/actions/runs/7982188180/job/21795271928?pr=85#step:4:328)
- install dependencies
> fix: linting

- .github/workflows/stale.yaml
> Use Keep label to exempt from stale action

- .github/release-drafter.yml
Add missing autolabeler config
> fix: add autolabeler config

- .github/workflows/scorecard.yml
- README.md
> chore: add OSSF scorecard github action and README badge

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-image.yml
- .github/workflows/linter.yaml
- .github/workflows/major-version-updater.yml
- .github/workflows/pr-title.yml
- .github/workflows/python-package.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
Closes #133, Closes #134, Closes #135, Close #137
To minimize the number of pull requests we get from dependabot, using groups will help with this.  Still want major semver changes to be single PRs so that stand out and we pay particular attention to them.
> chore: group dependabot dependency updates for minor/patch updates

- .github/workflows/release.yml
> fix: use correct image name for releases

- .github/workflows/release.yml
> fix: image name has underscore, not dash like repo

- .github/workflows/release.yml
> fix: use explicit image name for release

- .github/workflows/release.yml
> fix: need owner included with image name

- .github/workflows/python-package.yml
- README.md
> feat: drop support for python 3.9

- stale_repos.py
was mistakenly set from ORGANIZATION env var
> fix: use GH_TOKEN env var for token

- .github/release-drafter.yml
> chore: update semver

- .github/workflows/major-version-updater.yml
> fix: for tag update, especially if it already exists

- .github/workflows/major-version-updater.yml
> fix: use vars instead of env (not available at this point)

- .github/workflows/use-action.yml
- README.md
- action.yml
As discussed in #371, v6.0.0 of the action is still pulling the v5 Docker image. In this PR, I'm updating the metadata file to fix that, and also update other references to the Docker image and the action itself to consistently use v6.
cc @jmeridth
> fix: update version for action and Docker image
